In [18]:
import pandas as pd
import numpy as np
from datetime import datetime

print("Loan Approval Demo setup successful!")

Loan Approval Demo setup successful!

In [19]:
applicants = pd.DataFrame(
[{'application_id': 'L001',
  'name': 'Rahul Sharma',
  'monthly_income': 60000,
  'existing_emi': 8000,
  'loan_amount': 300000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 760,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L002',
  'name': 'Priya Verma',
  'monthly_income': 30000,
  'existing_emi': 10000,
  'loan_amount': 400000,
  'tenure_months': 36,
  'annual_interest_rate': 16,
  'credit_score': 650,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': True},
 {'application_id': 'L003',
  'name': 'Amit Kumar',
  'monthly_income': 45000,
  'existing_emi': 5000,
  'loan_amount': 200000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 720,
  'documents_complete': False,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L004',
  'name': 'Neha Patel',
  'monthly_income': 80000,
  'existing_emi': 12000,
  'loan_amount': 500000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 790,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L005',
  'name': 'Suresh Reddy',
  'monthly_income': 35000,
  'existing_emi': 6000,
  'loan_amount': 250000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 680,
  'documents_complete': True,
  'identity_verified': False,
  'overdue_flag': False},
 {'application_id': 'L006',
  'name': 'Anjali Singh',
  'monthly_income': 55000,
  'existing_emi': 7000,
  'loan_amount': 250000,
  'tenure_months': 36,
  'annual_interest_rate': 13.5,
  'credit_score': 735,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L007',
  'name': 'Vikram Mehta',
  'monthly_income': 95000,
  'existing_emi': 15000,
  'loan_amount': 650000,
  'tenure_months': 48,
  'annual_interest_rate': 12.5,
  'credit_score': 805,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L008',
  'name': 'Pooja Gupta',
  'monthly_income': 42000,
  'existing_emi': 9000,
  'loan_amount': 220000,
  'tenure_months': 36,
  'annual_interest_rate': 14.5,
  'credit_score': 710,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L009',
  'name': 'Karthik Nair',
  'monthly_income': 70000,
  'existing_emi': 10000,
  'loan_amount': 400000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 745,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L010',
  'name': 'Sneha Iyer',
  'monthly_income': 38000,
  'existing_emi': 5000,
  'loan_amount': 180000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 695,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L011',
  'name': 'Rohit Yadav',
  'monthly_income': 28000,
  'existing_emi': 9000,
  'loan_amount': 300000,
  'tenure_months': 36,
  'annual_interest_rate': 17,
  'credit_score': 640,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': True},
 {'application_id': 'L012',
  'name': 'Kavita Joshi',
  'monthly_income': 62000,
  'existing_emi': 6000,
  'loan_amount': 350000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 770,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L013',
  'name': 'Mohammed Imran',
  'monthly_income': 50000,
  'existing_emi': 8000,
  'loan_amount': 280000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 725,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L014',
  'name': 'Deepak Mishra',
  'monthly_income': 44000,
  'existing_emi': 6000,
  'loan_amount': 260000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 705,
  'documents_complete': False,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L015',
  'name': 'Divya Menon',
  'monthly_income': 85000,
  'existing_emi': 11000,
  'loan_amount': 550000,
  'tenure_months': 48,
  'annual_interest_rate': 12.8,
  'credit_score': 785,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L016',
  'name': 'Arjun Das',
  'monthly_income': 32000,
  'existing_emi': 4000,
  'loan_amount': 200000,
  'tenure_months': 36,
  'annual_interest_rate': 16,
  'credit_score': 675,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L017',
  'name': 'Meera Shah',
  'monthly_income': 58000,
  'existing_emi': 7000,
  'loan_amount': 300000,
  'tenure_months': 36,
  'annual_interest_rate': 13.5,
  'credit_score': 750,
  'documents_complete': True,
  'identity_verified': False,
  'overdue_flag': False},
 {'application_id': 'L018',
  'name': 'Ramesh Pillai',
  'monthly_income': 40000,
  'existing_emi': 12000,
  'loan_amount': 180000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 710,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L019',
  'name': 'Shweta Rao',
  'monthly_income': 72000,
  'existing_emi': 9000,
  'loan_amount': 420000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 765,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L020',
  'name': 'Nitin Choudhary',
  'monthly_income': 52000,
  'existing_emi': 6000,
  'loan_amount': 320000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 730,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L021',
  'name': 'Riya Sharma',
  'monthly_income': 42000,
  'existing_emi': 5000,
  'loan_amount': 200000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 720,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L022',
  'name': 'Aarav Singh',
  'monthly_income': 68000,
  'existing_emi': 9000,
  'loan_amount': 350000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 755,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L023',
  'name': 'Sunita Kumari',
  'monthly_income': 29000,
  'existing_emi': 7000,
  'loan_amount': 180000,
  'tenure_months': 36,
  'annual_interest_rate': 17,
  'credit_score': 640,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': True},
 {'application_id': 'L024',
  'name': 'Rajesh Gupta',
  'monthly_income': 56000,
  'existing_emi': 6000,
  'loan_amount': 300000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 705,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L025',
  'name': 'Priyanka Das',
  'monthly_income': 75000,
  'existing_emi': 12000,
  'loan_amount': 450000,
  'tenure_months': 48,
  'annual_interest_rate': 12.5,
  'credit_score': 780,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L026',
  'name': 'Manish Verma',
  'monthly_income': 38000,
  'existing_emi': 4000,
  'loan_amount': 220000,
  'tenure_months': 36,
  'annual_interest_rate': 16,
  'credit_score': 690,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L027',
  'name': 'Swati Mishra',
  'monthly_income': 47000,
  'existing_emi': 8000,
  'loan_amount': 260000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 715,
  'documents_complete': False,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L028',
  'name': 'Vivek Kumar',
  'monthly_income': 62000,
  'existing_emi': 10000,
  'loan_amount': 400000,
  'tenure_months': 48,
  'annual_interest_rate': 13.5,
  'credit_score': 740,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L029',
  'name': 'Pallavi Joshi',
  'monthly_income': 34000,
  'existing_emi': 3000,
  'loan_amount': 150000,
  'tenure_months': 24,
  'annual_interest_rate': 16,
  'credit_score': 665,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L030',
  'name': 'Sanjay Patel',
  'monthly_income': 88000,
  'existing_emi': 14000,
  'loan_amount': 600000,
  'tenure_months': 48,
  'annual_interest_rate': 12.5,
  'credit_score': 810,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L031',
  'name': 'Nisha Reddy',
  'monthly_income': 51000,
  'existing_emi': 6500,
  'loan_amount': 280000,
  'tenure_months': 36,
  'annual_interest_rate': 14.5,
  'credit_score': 730,
  'documents_complete': True,
  'identity_verified': False,
  'overdue_flag': False},
 {'application_id': 'L032',
  'name': 'Abhishek Jain',
  'monthly_income': 44000,
  'existing_emi': 7000,
  'loan_amount': 250000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 695,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': True},
 {'application_id': 'L033',
  'name': 'Komal Yadav',
  'monthly_income': 32000,
  'existing_emi': 5000,
  'loan_amount': 190000,
  'tenure_months': 36,
  'annual_interest_rate': 16,
  'credit_score': 655,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': True},
 {'application_id': 'L034',
  'name': 'Ajay Nair',
  'monthly_income': 71000,
  'existing_emi': 11000,
  'loan_amount': 420000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 765,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L035',
  'name': 'Shreya Kapoor',
  'monthly_income': 59000,
  'existing_emi': 6000,
  'loan_amount': 320000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 735,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L036',
  'name': 'Harish Menon',
  'monthly_income': 46000,
  'existing_emi': 9000,
  'loan_amount': 240000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 710,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L037',
  'name': 'Pankaj Tiwari',
  'monthly_income': 36000,
  'existing_emi': 4500,
  'loan_amount': 210000,
  'tenure_months': 36,
  'annual_interest_rate': 16,
  'credit_score': 680,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L038',
  'name': 'Ayesha Khan',
  'monthly_income': 64000,
  'existing_emi': 8000,
  'loan_amount': 380000,
  'tenure_months': 48,
  'annual_interest_rate': 13.5,
  'credit_score': 750,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L039',
  'name': 'Ravi Shankar',
  'monthly_income': 53000,
  'existing_emi': 7500,
  'loan_amount': 290000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 725,
  'documents_complete': False,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L040',
  'name': 'Tanvi Desai',
  'monthly_income': 82000,
  'existing_emi': 10000,
  'loan_amount': 500000,
  'tenure_months': 48,
  'annual_interest_rate': 12.8,
  'credit_score': 790,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L041',
  'name': 'Gaurav Malhotra',
  'monthly_income': 67000,
  'existing_emi': 12000,
  'loan_amount': 360000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 760,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L042',
  'name': 'Lakshmi Iyer',
  'monthly_income': 39000,
  'existing_emi': 3500,
  'loan_amount': 200000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 675,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L043',
  'name': 'Siddharth Rao',
  'monthly_income': 92000,
  'existing_emi': 15000,
  'loan_amount': 650000,
  'tenure_months': 48,
  'annual_interest_rate': 12.5,
  'credit_score': 820,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L044',
  'name': 'Farah Ali',
  'monthly_income': 41000,
  'existing_emi': 5000,
  'loan_amount': 230000,
  'tenure_months': 36,
  'annual_interest_rate': 16,
  'credit_score': 700,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': True},
 {'application_id': 'L045',
  'name': 'Ankit Sinha',
  'monthly_income': 48000,
  'existing_emi': 6500,
  'loan_amount': 270000,
  'tenure_months': 36,
  'annual_interest_rate': 14.5,
  'credit_score': 710,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L046',
  'name': 'Madhuri Pawar',
  'monthly_income': 57000,
  'existing_emi': 7000,
  'loan_amount': 310000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 745,
  'documents_complete': True,
  'identity_verified': False,
  'overdue_flag': False},
 {'application_id': 'L047',
  'name': 'Kiran Bhat',
  'monthly_income': 33000,
  'existing_emi': 3000,
  'loan_amount': 160000,
  'tenure_months': 24,
  'annual_interest_rate': 16,
  'credit_score': 660,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': True},
 {'application_id': 'L048',
  'name': 'Varun Chawla',
  'monthly_income': 76000,
  'existing_emi': 9000,
  'loan_amount': 430000,
  'tenure_months': 48,
  'annual_interest_rate': 13,
  'credit_score': 770,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L049',
  'name': 'Sonal Agarwal',
  'monthly_income': 61000,
  'existing_emi': 8500,
  'loan_amount': 340000,
  'tenure_months': 36,
  'annual_interest_rate': 13.5,
  'credit_score': 735,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L050',
  'name': 'Pradeep Shetty',
  'monthly_income': 49000,
  'existing_emi': 6000,
  'loan_amount': 260000,
  'tenure_months': 36,
  'annual_interest_rate': 15,
  'credit_score': 705,
  'documents_complete': False,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L051',
  'name': 'Simran Kaur',
  'monthly_income': 54000,
  'existing_emi': 7500,
  'loan_amount': 300000,
  'tenure_months': 36,
  'annual_interest_rate': 14,
  'credit_score': 720,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False},
 {'application_id': 'L052',
  'name': 'Naveen Kumar',
  'monthly_income': 37000,
  'existing_emi': 4000,
  'loan_amount': 190000,
  'tenure_months': 36,
  'annual_interest_rate': 16,
  'credit_score': 685,
  'documents_complete': True,
  'identity_verified': True,
  'overdue_flag': False}]
)

display(applicants)

,application_id,name,monthly_income,existing_emi,loan_amount,tenure_months,annual_interest_rate,credit_score,documents_complete,identity_verified,overdue_flag
0,L001,Rahul Sharma,60000,8000,300000,36,14.0,760,True,True,False
1,L002,Priya Verma,30000,10000,400000,36,16.0,650,True,True,True
2,L003,Amit Kumar,45000,5000,200000,36,14.0,720,False,True,False
3,L004,Neha Patel,80000,12000,500000,48,13.0,790,True,True,False
4,L005,Suresh Reddy,35000,6000,250000,36,15.0,680,True,False,False
5,L006,Anjali Singh,55000,7000,250000,36,13.5,735,True,True,False
6,L007,Vikram Mehta,95000,15000,650000,48,12.5,805,True,True,False
7,L008,Pooja Gupta,42000,9000,220000,36,14.5,710,True,True,False
8,L009,Karthik Nair,70000,10000,400000,48,13.0,745,True,True,False
9,L010,Sneha Iyer,38000,5000,180000,36,15.0,695,True,True,False
10,L011,Rohit Yadav,28000,9000,300000,36,17.0,640,True,True,True
11,L012,Kavita Joshi,62000,6000,350000,48,13.0,770,True,True,False
12,L013,Mohammed Imran,50000,8000,280000,36,14.0,725,True,True,False
13,L014,Deepak Mishra,44000,6000,260000,36,15.0,705,False,True,False
14,L015,Divya Menon,85000,11000,550000,48,12.8,785,True,True,False
15,L016,Arjun Das,32000,4000,200000,36,16.0,675,True,True,False
16,L017,Meera Shah,58000,7000,300000,36,13.5,750,True,False,False
17,L018,Ramesh Pillai,40000,12000,180000,36,15.0,710,True,True,False
18,L019,Shweta Rao,72000,9000,420000,48,13.0,765,True,True,False
19,L020,Nitin Choudhary,52000,6000,320000,36,14.0,730,True,True,False
20,L021,Riya Sharma,42000,5000,200000,36,15.0,720,True,True,False
21,L022,Aarav Singh,68000,9000,350000,48,13.0,755,True,True,False
22,L023,Sunita Kumari,29000,7000,180000,36,17.0,640,True,True,True
23,L024,Rajesh Gupta,56000,6000,300000,36,14.0,705,True,True,False
24,L025,Priyanka Das,75000,12000,450000,48,12.5,780,True,True,False
25,L026,Manish Verma,38000,4000,220000,36,16.0,690,True,True,False
26,L027,Swati Mishra,47000,8000,260000,36,15.0,715,False,True,False
27,L028,Vivek Kumar,62000,10000,400000,48,13.5,740,True,True,False
28,L029,Pallavi Joshi,34000,3000,150000,24,16.0,665,True,True,False
29,L030,Sanjay Patel,88000,14000,600000,48,12.5,810,True,True,False
30,L031,Nisha Reddy,51000,6500,280000,36,14.5,730,True,False,False
31,L032,Abhishek Jain,44000,7000,250000,36,15.0,695,True,True,True
32,L033,Komal Yadav,32000,5000,190000,36,16.0,655,True,True,True
33,L034,Ajay Nair,71000,11000,420000,48,13.0,765,True,True,False
34,L035,Shreya Kapoor,59000,6000,320000,36,14.0,735,True,True,False
35,L036,Harish Menon,46000,9000,240000,36,15.0,710,True,True,False
36,L037,Pankaj Tiwari,36000,4500,210000,36,16.0,680,True,True,False
37,L038,Ayesha Khan,64000,8000,380000,48,13.5,750,True,True,False
38,L039,Ravi Shankar,53000,7500,290000,36,14.0,725,False,True,False
39,L040,Tanvi Desai,82000,10000,500000,48,12.8,790,True,True,False
40,L041,Gaurav Malhotra,67000,12000,360000,48,13.0,760,True,True,False
41,L042,Lakshmi Iyer,39000,3500,200000,36,15.0,675,True,True,False
42,L043,Siddharth Rao,92000,15000,650000,48,12.5,820,True,True,False
43,L044,Farah Ali,41000,5000,230000,36,16.0,700,True,True,True
44,L045,Ankit Sinha,48000,6500,270000,36,14.5,710,True,True,False
45,L046,Madhuri Pawar,57000,7000,310000,36,14.0,745,True,False,False
46,L047,Kiran Bhat,33000,3000,160000,24,16.0,660,True,True,True
47,L048,Varun Chawla,76000,9000,430000,48,13.0,770,True,True,False
48,L049,Sonal Agarwal,61000,8500,340000,36,13.5,735,True,True,False
49,L050,Pradeep Shetty,49000,6000,260000,36,15.0,705,False,True,False
50,L051,Simran Kaur,54000,7500,300000,36,14.0,720,True,True,False
51,L052,Naveen Kumar,37000,4000,190000,36,16.0,685,True,True,False

In [20]:
def calculate_emi(principal, annual_interest_rate, tenure_months):
    monthly_rate = annual_interest_rate / 12 / 100

    if tenure_months <= 0 or principal <= 0:
        raise ValueError("Loan amount and tenure must be positive.")

    if monthly_rate == 0:
        return principal / tenure_months

    emi = (
        principal
        * monthly_rate
        * (1 + monthly_rate) ** tenure_months
        / ((1 + monthly_rate) ** tenure_months - 1)
    )

    return round(emi, 2)


# Test the EMI function
emi = calculate_emi(
    principal=300000,
    annual_interest_rate=14,
    tenure_months=36
)

print("Proposed monthly EMI: ₹", emi)

Proposed monthly EMI: ₹ 10253.29

In [21]:
def calculate_affordability(applicant):
    emi = calculate_emi(
        applicant["loan_amount"],
        applicant["annual_interest_rate"],
        applicant["tenure_months"]
    )

    total_monthly_obligations = applicant["existing_emi"] + emi

    foir = (
        total_monthly_obligations
        / applicant["monthly_income"]
    ) * 100

    disposable_income = (
        applicant["monthly_income"]
        - total_monthly_obligations
    )

    return {
        "proposed_emi": round(emi, 2),
        "total_monthly_obligations": round(
            total_monthly_obligations, 2
        ),
        "foir_percent": round(foir, 2),
        "disposable_income": round(disposable_income, 2)
    }


# Test using the first applicant
test_result = calculate_affordability(applicants.iloc[0])

print(test_result)

{'proposed_emi': np.float64(10253.29), 'total_monthly_obligations': np.float64(18253.29), 'foir_percent': np.float64(30.42), 'disposable_income': np.float64(41746.71)}

In [22]:
DEMO_POLICY = {
    "minimum_credit_score": 700,
    "maximum_foir_percent": 40
}

print("Demo credit policy loaded:")
print(DEMO_POLICY)

Demo credit policy loaded:
{'minimum_credit_score': 700, 'maximum_foir_percent': 40}

In [23]:
def assess_loan(applicant):
    affordability = calculate_affordability(applicant)

    findings = []
    risk_flags = []

    # Agent 1: Document Intelligence
    if not applicant["documents_complete"]:
        findings.append(
            "Required documents are incomplete."
        )

    # Agent 2: Verification and Policy
    if not applicant["identity_verified"]:
        findings.append(
            "Identity verification is pending or unsuccessful."
        )

    if applicant["credit_score"] < DEMO_POLICY["minimum_credit_score"]:
        risk_flags.append(
            "Credit score is below the configured demo threshold."
        )

    if affordability["foir_percent"] > DEMO_POLICY["maximum_foir_percent"]:
        risk_flags.append(
            "FOIR exceeds the configured demo threshold."
        )

    if applicant["overdue_flag"]:
        risk_flags.append(
            "Simulated credit bureau indicates overdue repayment."
        )

    # Agent 3: Credit Assessment
    # Missing mandatory checks take the case to manual review.
    if findings:
        recommendation = "MANUAL REVIEW"
        reason = "Resolve pending document or identity checks."

    elif risk_flags:
        recommendation = "REFER FOR CREDIT REVIEW"
        reason = "One or more configured risk rules were triggered."

    else:
        recommendation = "RECOMMEND APPROVAL"
        reason = (
            "Configured demo checks passed. "
            "Credit officer approval is still required."
        )

    return {
        "application_id": applicant["application_id"],
        "applicant_name": applicant["name"],
        **affordability,
        "credit_score": applicant["credit_score"],
        "document_status": (
            "Complete"
            if applicant["documents_complete"]
            else "Incomplete"
        ),
        "identity_status": (
            "Verified"
            if applicant["identity_verified"]
            else "Pending / unsuccessful"
        ),
        "findings": findings,
        "risk_flags": risk_flags,
        "recommendation": recommendation,
        "reason": reason,
        "final_approval": "Pending credit officer decision"
    }


# Assess the first applicant
result = assess_loan(applicants.iloc[0])

for key, value in result.items():
    print(f"{key}: {value}")

application_id: L001
applicant_name: Rahul Sharma
proposed_emi: 10253.29
total_monthly_obligations: 18253.29
foir_percent: 30.42
disposable_income: 41746.71
credit_score: 760
document_status: Complete
identity_status: Verified
findings: []
risk_flags: []
recommendation: RECOMMEND APPROVAL
reason: Configured demo checks passed. Credit officer approval is still required.
final_approval: Pending credit officer decision

In [24]:
results = pd.DataFrame([
    assess_loan(applicant)
    for _, applicant in applicants.iterrows()
])

display(
    results[
        [
            "application_id",
            "applicant_name",
            "proposed_emi",
            "foir_percent",
            "credit_score",
            "recommendation",
            "reason"
        ]
    ]
)

,application_id,applicant_name,proposed_emi,foir_percent,credit_score,recommendation,reason
0,L001,Rahul Sharma,10253.29,30.42,760,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
1,L002,Priya Verma,14062.81,80.21,650,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
2,L003,Amit Kumar,6835.53,26.30,720,MANUAL REVIEW,Resolve pending document or identity checks.
3,L004,Neha Patel,13413.75,31.77,790,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
4,L005,Suresh Reddy,8666.33,41.90,680,MANUAL REVIEW,Resolve pending document or identity checks.
5,L006,Anjali Singh,8483.82,28.15,735,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
6,L007,Vikram Mehta,17277.00,33.98,805,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
7,L008,Pooja Gupta,7572.62,39.46,710,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
8,L009,Karthik Nair,10731.00,29.62,745,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
9,L010,Sneha Iyer,6239.76,29.58,695,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
10,L011,Rohit Yadav,10695.82,70.34,640,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
11,L012,Kavita Joshi,9389.62,24.82,770,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
12,L013,Mohammed Imran,9569.74,35.14,725,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
13,L014,Deepak Mishra,9012.99,34.12,705,MANUAL REVIEW,Resolve pending document or identity checks.
14,L015,Divya Menon,14700.59,30.24,785,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
15,L016,Arjun Das,7031.41,34.47,675,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
16,L017,Meera Shah,10180.59,29.62,750,MANUAL REVIEW,Resolve pending document or identity checks.
17,L018,Ramesh Pillai,6239.76,45.60,710,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
18,L019,Shweta Rao,11267.55,28.15,765,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
19,L020,Nitin Choudhary,10936.84,32.57,730,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
20,L021,Riya Sharma,6933.07,28.41,720,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
21,L022,Aarav Singh,9389.62,27.04,755,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
22,L023,Sunita Kumari,6417.49,46.27,640,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
23,L024,Rajesh Gupta,10253.29,29.02,705,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
24,L025,Priyanka Das,11961.00,31.95,780,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
25,L026,Manish Verma,7734.55,30.88,690,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
26,L027,Swati Mishra,9012.99,36.20,715,MANUAL REVIEW,Resolve pending document or identity checks.
27,L028,Vivek Kumar,10830.53,33.60,740,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
28,L029,Pallavi Joshi,7344.47,30.42,665,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
29,L030,Sanjay Patel,15948.00,34.03,810,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
30,L031,Nisha Reddy,9637.87,31.64,730,MANUAL REVIEW,Resolve pending document or identity checks.
31,L032,Abhishek Jain,8666.33,35.61,695,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
32,L033,Komal Yadav,6679.84,36.50,655,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
33,L034,Ajay Nair,11267.55,31.36,765,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
34,L035,Shreya Kapoor,10936.84,28.71,735,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
35,L036,Harish Menon,8319.68,37.65,710,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
36,L037,Pankaj Tiwari,7382.98,33.01,680,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
37,L038,Ayesha Khan,10289.00,28.58,750,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
38,L039,Ravi Shankar,9911.51,32.85,725,MANUAL REVIEW,Resolve pending document or identity checks.
39,L040,Tanvi Desai,13364.17,28.49,790,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
40,L041,Gaurav Malhotra,9657.90,32.33,760,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
41,L042,Lakshmi Iyer,6933.07,26.75,675,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
42,L043,Siddharth Rao,17277.00,35.08,820,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
43,L044,Farah Ali,8086.12,31.92,700,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
44,L045,Ankit Sinha,9293.66,32.90,710,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
45,L046,Madhuri Pawar,10595.07,30.87,745,MANUAL REVIEW,Resolve pending document or identity checks.
46,L047,Kiran Bhat,7834.10,32.83,660,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.
47,L048,Varun Chawla,11535.82,27.02,770,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
48,L049,Sonal Agarwal,11538.00,32.85,735,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
49,L050,Pradeep Shetty,9012.99,30.64,705,MANUAL REVIEW,Resolve pending document or identity checks.
50,L051,Simran Kaur,10253.29,32.88,720,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...
51,L052,Naveen Kumar,6679.84,28.86,685,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.

In [25]:
assert calculate_emi(300000, 14, 36) > 0

assert (
    assess_loan(applicants.iloc[0])["recommendation"]
    == "RECOMMEND APPROVAL"
)

assert (
    assess_loan(applicants.iloc[1])["recommendation"]
    == "REFER FOR CREDIT REVIEW"
)

assert (
    assess_loan(applicants.iloc[2])["recommendation"]
    == "MANUAL REVIEW"
)

assert (
    assess_loan(applicants.iloc[4])["recommendation"]
    == "MANUAL REVIEW"
)

print("All initial tests passed!")

All initial tests passed!

In [26]:
results.to_csv("loan_assessment_results.csv", index=False)

print("Assessment results saved successfully.")

Assessment results saved successfully.

In [27]:
from IPython.display import FileLink, display

display(FileLink("loan_assessment_results.csv"))

C:\Users\91882\loan_assessment_results.csv

In [28]:
!pip -q install streamlit

In [49]:
%%writefile app.py
import streamlit as st
import pandas as pd
from google.cloud import bigquery

# Demo policy used by Agent 2 (Verification and Policy)
DEMO_POLICY = {
    "minimum_credit_score": 700,
    "maximum_foir_percent": 40
}

st.set_page_config(
    page_title="LoanPilot AI",
    page_icon="🏦",
    layout="wide"
)

st.title("LoanPilot AI")
st.caption(
    "AI-assisted personal loan assessment | "
    "Fictional data and simulated checks"
)


# Load applicant data from BigQuery
PROJECT_ID = "loanapp-0911"
TABLE_ID = "loanapp-0911.loan_demo.loan_master_data"

@st.cache_data(ttl=60)
def load_loan_data():
    client = bigquery.Client(project=PROJECT_ID)

    query = f"""
        SELECT
            application_id,
            name,
            monthly_income,
            existing_emi,
            loan_amount,
            tenure_months,
            annual_interest_rate,
            credit_score,
            documents_complete,
            identity_verified,
            overdue_flag
        FROM `{TABLE_ID}`
        ORDER BY application_id
    """

    return client.query(query).to_dataframe()

applicants = load_loan_data()

if applicants.empty:
    st.warning("No loan applications were found in BigQuery.")
    st.stop()

st.success(
    f"Loaded {len(applicants)} loan applications from BigQuery."
)




st.dataframe(applicants, use_container_width=True)

def calculate_emi(principal, annual_rate, months):
    r = annual_rate / 1200
    if principal <= 0 or months <= 0:
        raise ValueError("Principal and tenure must be positive.")
    if r == 0:
        return principal / months
    return principal * r * (1 + r)**months / ((1 + r)**months - 1)

def assess(row):
    emi = calculate_emi(
        row["loan_amount"],
        row["annual_interest_rate"],
        row["tenure_months"]
    )
    foir = (row["existing_emi"] + emi) / row["monthly_income"] * 100

    findings = []
    risks = []

    if not row["documents_complete"]:
        findings.append("Required documents are incomplete.")

    if not row["identity_verified"]:
        findings.append("Identity verification is unresolved.")

    if row["credit_score"] < 700:
        risks.append("Credit score is below the demo threshold.")

    if foir > 40:
        risks.append("FOIR exceeds the demo threshold.")

    if row["overdue_flag"]:
        risks.append("Simulated overdue flag detected.")

    if findings:
        recommendation = "MANUAL REVIEW"
    elif risks:
        recommendation = "REFER FOR CREDIT REVIEW"
    else:
        recommendation = "RECOMMEND APPROVAL"

    return {
        "emi": round(emi, 2),
        "foir": round(foir, 2),
        "findings": findings,
        "risks": risks,
        "recommendation": recommendation
    }

st.sidebar.header("Navigation")
page = st.sidebar.radio(
    "Select page",
    ["Loan Dashboard", "Approach Story", "Architecture", "About / FAQ"]
)

if page == "Loan Dashboard":
    st.subheader("Loan Operations Dashboard")

    selected_id = st.selectbox(
        "Select application",
        applicants["application_id"]
    )

    row = applicants.loc[
        applicants["application_id"] == selected_id
    ].iloc[0]

    result = assess(row)

    c1, c2, c3 = st.columns(3)
    c1.metric("Monthly income", f"₹{row['monthly_income']:,.0f}")
    c2.metric("Proposed EMI", f"₹{result['emi']:,.0f}")
    c3.metric("FOIR", f"{result['foir']:.1f}%")

    st.subheader("Applicant profile")
    st.write({
        "Application ID": row["application_id"],
        "Applicant": row["name"],
        "Loan amount": f"₹{row['loan_amount']:,.0f}",
        "Tenure": f"{row['tenure_months']} months",
        "Simulated credit score": row["credit_score"]
    })

    st.subheader("Agent activity")
    st.write("1. Document Intelligence Agent: checked document status.")
    st.write("2. Verification and Policy Agent: checked simulated identity and bureau results.")
    st.write("3. Credit Assessment Agent: calculated EMI and FOIR.")

    st.subheader("Recommendation")
    st.info(result["recommendation"])

    if result["findings"]:
        st.warning("Pending checks: " + " ".join(result["findings"]))

    if result["risks"]:
        st.warning("Risk flags: " + " ".join(result["risks"]))

    st.caption(
        "Illustrative rules only. All external checks are simulated. "
        "A credit officer must make the actual decision."
    )

    st.subheader("Credit officer review")
    officer_action = st.selectbox(
        "Record review outcome",
        ["Pending", "Approve", "Reject", "Request more information"]
    )
    review_reason = st.text_area("Review comments / reason")

    if st.button("Record review"):
        if officer_action == "Pending":
            st.warning("Choose a review outcome before recording.")
        elif not review_reason.strip():
            st.warning("Enter a reason for the review decision.")
        else:
            st.success(
                f"Demo review recorded: {officer_action}. "
                "This does not execute a real sanction or disbursement."
            )
            st.write("Reason:", review_reason)

elif page == "Approach Story":
    st.header("From fragmented data to informed decisions")

    st.subheader("Act 1 — Build a unified data foundation")
    st.write(
        "Bring customer records, loan history, policy documents "
        "and simulated external verification responses together. "
        "BigQuery is the planned analytical data layer."
    )

    st.subheader("Act 2 — Apply AI-assisted workflows")
    st.write(
        "Document checks, policy lookup and affordability calculations "
        "produce findings and a recommendation with reasons. "
        "A credit officer retains decision authority."
    )

elif page == "Architecture":
    st.header("Solution Architecture")

    st.code("""
Customer applications / PDFs / Core banking / Mock APIs
                         |
                         v
                Data ingestion layer
                         |
                         v
             BigQuery lakehouse (planned)
                         |
                         v
       Document -> Verification -> Credit assessment
                         |
                         v
               Streamlit application
                         |
                         v
              Credit officer review

Governance: access controls, policy versioning, audit logs,
data quality, explainability and human oversight.
    """)

    st.caption(
        "This is a proposed architecture. BigQuery and production "
        "integrations are not connected in this prototype."
    )

else:
    st.header("About LoanPilot AI")
    st.write(
        "A fictional point-of-view demo of AI-assisted personal "
        "loan assessment for salaried applicants."
    )
    st.subheader("Frequently asked questions")
    st.write("Are the applicants real? No, all applicants are fictional.")
    st.write("Is CIBIL connected? No, bureau results are simulated.")
    st.write("Does AI approve loans? No, an authorized credit officer "
             "must make the actual decision.")

Overwriting app.py

In [50]:
import os
import sys
import subprocess
import time

# Confirm app.py exists before launching Streamlit
if not os.path.exists('app.py'):
    raise FileNotFoundError('app.py was not found. Run the %%writefile app.py cell first.')

# Start Streamlit in the background so this notebook cell can finish
log_file = open('streamlit_log.txt', 'w', encoding='utf-8')
process = subprocess.Popen(
    [sys.executable, '-m', 'streamlit', 'run', 'app.py',
     '--server.port', '8501', '--server.headless', 'true'],
    stdout=log_file,
    stderr=subprocess.STDOUT,
    creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if os.name == 'nt' else 0
)

time.sleep(3)
print('Streamlit launch command sent.')
print('Open this address in your browser: http://localhost:8501')
print('If the page does not open, inspect streamlit_log.txt for the error.')
print('Process ID:', process.pid)

Streamlit launch command sent.
Open this address in your browser: http://localhost:8501
If the page does not open, inspect streamlit_log.txt for the error.
Process ID: 16432

In [51]:
import os
print('Working folder:', os.getcwd())
print('app.py exists:', os.path.exists('app.py'))
if os.path.exists('app.py'):
    print('app.py size:', os.path.getsize('app.py'), 'bytes')

Working folder: C:\Users\91882
app.py exists: True
app.py size: 7372 bytes

In [52]:
import sys
import subprocess
import time
import os

if not os.path.exists("app.py"):
    raise FileNotFoundError("app.py is missing from the current folder.")

log_file = open("streamlit_log.txt", "w", encoding="utf-8")

process = subprocess.Popen(
    [
        sys.executable, "-m", "streamlit", "run", "app.py",
        "--server.port", "8501",
        "--server.headless", "true"
    ],
    stdout=log_file,
    stderr=subprocess.STDOUT
)

time.sleep(3)

print("LoanPilot AI launch attempted.")
print("Open: http://localhost:8501")
print("Process ID:", process.pid)

LoanPilot AI launch attempted.
Open: http://localhost:8501
Process ID: 6788

In [53]:

from pathlib import Path
import pandas as pd

# Make sure the main notebook variables exist
assert "applicants" in globals(), "Run the applicants data cell first."
assert "results" in globals(), "Run the assessment results cell first."

data_dir = Path("loanpilot_data")
data_dir.mkdir(exist_ok=True)

# Table 1: Applicant profiles
applicant_profiles = applicants[
    [
        "application_id",
        "name",
        "monthly_income",
        "existing_emi"
    ]
].copy()

# Table 2: Loan application details
loan_applications = applicants[
    [
        "application_id",
        "loan_amount",
        "tenure_months",
        "annual_interest_rate"
    ]
].copy()

# Table 3: Verification and mock bureau checks
verification_checks = applicants[
    [
        "application_id",
        "credit_score",
        "documents_complete",
        "identity_verified",
        "overdue_flag"
    ]
].copy()

# Table 4: Results generated by your existing assessment function
assessment_results = results.copy()

# Make list-valued columns safe to export to CSV
for col in ["findings", "risk_flags"]:
    if col in assessment_results.columns:
        assessment_results[col] = assessment_results[col].apply(
            lambda x: "; ".join(map(str, x))
            if isinstance(x, (list, tuple, set))
            else x
        )

# Save the tables
tables = {
    "applicant_profiles.csv": applicant_profiles,
    "loan_applications.csv": loan_applications,
    "verification_checks.csv": verification_checks,
    "loan_assessment_results.csv": assessment_results
}

for filename, df in tables.items():
    df.to_csv(data_dir / filename, index=False)

    # Read it back to confirm that the file is usable
    check = pd.read_csv(data_dir / filename)

    assert len(check) == len(df), f"Row-count mismatch: {filename}"
    print(f"OK: {filename} | {len(check)} rows | {len(check.columns)} columns")

print("\nData export and validation completed.")
print("Folder:", data_dir.resolve())

OK: applicant_profiles.csv | 52 rows | 4 columns
OK: loan_applications.csv | 52 rows | 4 columns
OK: verification_checks.csv | 52 rows | 5 columns
OK: loan_assessment_results.csv | 52 rows | 14 columns

Data export and validation completed.
Folder: C:\Users\91882\loanpilot_data

In [54]:

%pip install google-cloud-bigquery db-dtypes pandas

Requirement already satisfied: google-cloud-bigquery in C:\ANACONDA\Lib\site-packages (3.46.2)
Requirement already satisfied: db-dtypes in C:\ANACONDA\Lib\site-packages (1.9.0)
Requirement already satisfied: pandas in C:\ANACONDA\Lib\site-packages (3.0.3)
Requirement already satisfied: google-api-core<3.0.0,>=2.28.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (2.43.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in C:\ANACONDA\Lib\site-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.62.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.8.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.11.0)
Requirement already satisfied: packaging>=24.2.0 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (26.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.34.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.76.0)
Requirement already satisfied: protobuf<8.0.0,>=6.33.5 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.26.1 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.29.0)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.44.0 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.45.1)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.84.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.84.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\ANACONDA\Lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in C:\ANACONDA\Lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (49.0.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in C:\ANACONDA\Lib\site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.9.0)
Requirement already satisfied: typing-extensions~=4.12 in C:\ANACONDA\Lib\site-packages (from grpcio<2.0.0,>=1.59.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\ANACONDA\Lib\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.6.17)
Requirement already satisfied: numpy>=1.24.0 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (2.4.6)
Requirement already satisfied: pyarrow>=13.0.0 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (23.0.1)
Requirement already satisfied: tzdata in C:\ANACONDA\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: cffi>=2.0.0 in C:\ANACONDA\Lib\site-packages (from cryptography>=41.0.5->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.1.0)
Requirement already satisfied: pycparser in C:\ANACONDA\Lib\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\ANACONDA\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.4)
Note: you may need to restart the kernel to use updated packages.

In [55]:

from google.cloud import bigquery

PROJECT_ID = "loanapp-0911"
TABLE_ID = "loanapp-0911.loan_demo.loan_master_data"

client = bigquery.Client(project=PROJECT_ID)

query = f"""
SELECT *
FROM `{TABLE_ID}`
LIMIT 20
"""

df = client.query(query).to_dataframe()

print("Rows retrieved:", len(df))
display(df)

C:\ANACONDA\Lib\site-packages\google\auth\_default.py:113: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

Rows retrieved: 20

,application_id,name,monthly_income,existing_emi,loan_amount,tenure_months,annual_interest_rate,credit_score,documents_complete,identity_verified,...,total_monthly_obligations,foir_percent,disposable_income,document_status,identity_status,findings,risk_flags,recommendation,reason,final_approval
0,L005,Suresh Reddy,35000,6000,250000,36,15.0,680,True,False,...,14666.33,41.90,20333.67,Complete,Pending / unsuccessful,Identity verification is pending or unsuccessful.,Credit score is below the configured demo thre...,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
1,L014,Deepak Mishra,44000,6000,260000,36,15.0,705,False,True,...,15012.99,34.12,28987.01,Incomplete,Verified,Required documents are incomplete.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
2,L050,Pradeep Shetty,49000,6000,260000,36,15.0,705,False,True,...,15012.99,30.64,33987.01,Incomplete,Verified,Required documents are incomplete.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
3,L027,Swati Mishra,47000,8000,260000,36,15.0,715,False,True,...,17012.99,36.20,29987.01,Incomplete,Verified,Required documents are incomplete.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
4,L003,Amit Kumar,45000,5000,200000,36,14.0,720,False,True,...,11835.53,26.30,33164.47,Incomplete,Verified,Required documents are incomplete.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
5,L039,Ravi Shankar,53000,7500,290000,36,14.0,725,False,True,...,17411.51,32.85,35588.49,Incomplete,Verified,Required documents are incomplete.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
6,L031,Nisha Reddy,51000,6500,280000,36,14.5,730,True,False,...,16137.87,31.64,34862.13,Complete,Pending / unsuccessful,Identity verification is pending or unsuccessful.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
7,L046,Madhuri Pawar,57000,7000,310000,36,14.0,745,True,False,...,17595.07,30.87,39404.93,Complete,Pending / unsuccessful,Identity verification is pending or unsuccessful.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
8,L017,Meera Shah,58000,7000,300000,36,13.5,750,True,False,...,17180.59,29.62,40819.41,Complete,Pending / unsuccessful,Identity verification is pending or unsuccessful.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
9,L024,Rajesh Gupta,56000,6000,300000,36,14.0,705,True,True,...,16253.29,29.02,39746.71,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
10,L008,Pooja Gupta,42000,9000,220000,36,14.5,710,True,True,...,16572.62,39.46,25427.38,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
11,L036,Harish Menon,46000,9000,240000,36,15.0,710,True,True,...,17319.68,37.65,28680.32,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
12,L045,Ankit Sinha,48000,6500,270000,36,14.5,710,True,True,...,15793.66,32.90,32206.34,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
13,L021,Riya Sharma,42000,5000,200000,36,15.0,720,True,True,...,11933.07,28.41,30066.93,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
14,L051,Simran Kaur,54000,7500,300000,36,14.0,720,True,True,...,17753.29,32.88,36246.71,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
15,L013,Mohammed Imran,50000,8000,280000,36,14.0,725,True,True,...,17569.74,35.14,32430.26,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
16,L020,Nitin Choudhary,52000,6000,320000,36,14.0,730,True,True,...,16936.84,32.57,35063.16,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
17,L006,Anjali Singh,55000,7000,250000,36,13.5,735,True,True,...,15483.82,28.15,39516.18,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
18,L035,Shreya Kapoor,59000,6000,320000,36,14.0,735,True,True,...,16936.84,28.71,42063.16,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
19,L049,Sonal Agarwal,61000,8500,340000,36,13.5,735,True,True,...,20038.00,32.85,40962.00,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision

In [56]:

from google.cloud import bigquery

PROJECT_ID = "loanapp-0911"
TABLE_ID = "loanapp-0911.loan_demo.loan_master_data"

client = bigquery.Client(project=PROJECT_ID)

query = f"""
SELECT
    COUNT(*) AS total_applications,
    COUNT(DISTINCT application_id) AS unique_applications
FROM `{TABLE_ID}`
"""

result = client.query(query).to_dataframe()
display(result)

C:\ANACONDA\Lib\site-packages\google\auth\_default.py:113: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

   total_applications  unique_applications
0                  52                   52

In [57]:

from google.cloud import bigquery

PROJECT_ID = "loanapp-0911"
TABLE_ID = "loanapp-0911.loan_demo.loan_master_data"

client = bigquery.Client(project=PROJECT_ID)

query = f"""
SELECT *
FROM `{TABLE_ID}`
ORDER BY application_id
"""

loan_df = client.query(query).to_dataframe()

print("BigQuery connection successful")
print("Total applications:", len(loan_df))
print("Columns:", loan_df.columns.tolist())
display(loan_df.head())

C:\ANACONDA\Lib\site-packages\google\auth\_default.py:113: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

BigQuery connection successful
Total applications: 52
Columns: ['application_id', 'name', 'monthly_income', 'existing_emi', 'loan_amount', 'tenure_months', 'annual_interest_rate', 'credit_score', 'documents_complete', 'identity_verified', 'overdue_flag', 'proposed_emi', 'total_monthly_obligations', 'foir_percent', 'disposable_income', 'document_status', 'identity_status', 'findings', 'risk_flags', 'recommendation', 'reason', 'final_approval']

,application_id,name,monthly_income,existing_emi,loan_amount,tenure_months,annual_interest_rate,credit_score,documents_complete,identity_verified,...,total_monthly_obligations,foir_percent,disposable_income,document_status,identity_status,findings,risk_flags,recommendation,reason,final_approval
0,L001,Rahul Sharma,60000,8000,300000,36,14.0,760,True,True,...,18253.29,30.42,41746.71,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
1,L002,Priya Verma,30000,10000,400000,36,16.0,650,True,True,...,24062.81,80.21,5937.19,Complete,Verified,NaN,Credit score is below the configured demo thre...,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.,Pending credit officer decision
2,L003,Amit Kumar,45000,5000,200000,36,14.0,720,False,True,...,11835.53,26.30,33164.47,Incomplete,Verified,Required documents are incomplete.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
3,L004,Neha Patel,80000,12000,500000,48,13.0,790,True,True,...,25413.75,31.77,54586.25,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
4,L005,Suresh Reddy,35000,6000,250000,36,15.0,680,True,False,...,14666.33,41.90,20333.67,Complete,Pending / unsuccessful,Identity verification is pending or unsuccessful.,Credit score is below the configured demo thre...,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision

In [58]:

from google.cloud import bigquery

PROJECT_ID = "loanapp-0911"
TABLE_ID = "loanapp-0911.loan_demo.loan_master_data"

client = bigquery.Client(project=PROJECT_ID)

query = f"""
SELECT *
FROM `{TABLE_ID}`
ORDER BY application_id
"""

loan_df = client.query(query).to_dataframe()

print("BigQuery connection successful!")
print("Total applications:", len(loan_df))
print("Columns:", loan_df.columns.tolist())

display(loan_df.head())

C:\ANACONDA\Lib\site-packages\google\auth\_default.py:113: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

BigQuery connection successful!
Total applications: 52
Columns: ['application_id', 'name', 'monthly_income', 'existing_emi', 'loan_amount', 'tenure_months', 'annual_interest_rate', 'credit_score', 'documents_complete', 'identity_verified', 'overdue_flag', 'proposed_emi', 'total_monthly_obligations', 'foir_percent', 'disposable_income', 'document_status', 'identity_status', 'findings', 'risk_flags', 'recommendation', 'reason', 'final_approval']

,application_id,name,monthly_income,existing_emi,loan_amount,tenure_months,annual_interest_rate,credit_score,documents_complete,identity_verified,...,total_monthly_obligations,foir_percent,disposable_income,document_status,identity_status,findings,risk_flags,recommendation,reason,final_approval
0,L001,Rahul Sharma,60000,8000,300000,36,14.0,760,True,True,...,18253.29,30.42,41746.71,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
1,L002,Priya Verma,30000,10000,400000,36,16.0,650,True,True,...,24062.81,80.21,5937.19,Complete,Verified,NaN,Credit score is below the configured demo thre...,REFER FOR CREDIT REVIEW,One or more configured risk rules were triggered.,Pending credit officer decision
2,L003,Amit Kumar,45000,5000,200000,36,14.0,720,False,True,...,11835.53,26.30,33164.47,Incomplete,Verified,Required documents are incomplete.,NaN,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision
3,L004,Neha Patel,80000,12000,500000,48,13.0,790,True,True,...,25413.75,31.77,54586.25,Complete,Verified,NaN,NaN,RECOMMEND APPROVAL,Configured demo checks passed. Credit officer ...,Pending credit officer decision
4,L005,Suresh Reddy,35000,6000,250000,36,15.0,680,True,False,...,14666.33,41.90,20333.67,Complete,Pending / unsuccessful,Identity verification is pending or unsuccessful.,Credit score is below the configured demo thre...,MANUAL REVIEW,Resolve pending document or identity checks.,Pending credit officer decision

In [59]:

%pip install -U google-cloud-bigquery-storage db-dtypes

Requirement already satisfied: google-cloud-bigquery-storage in C:\ANACONDA\Lib\site-packages (2.43.0)
Requirement already satisfied: db-dtypes in C:\ANACONDA\Lib\site-packages (1.9.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.28.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (2.43.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery-storage) (2.62.0)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery-storage) (1.84.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.26.1 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery-storage) (1.29.0)
Requirement already satisfied: protobuf<8.0.0,>=6.33.5 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery-storage) (6.33.5)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (1.76.0)
Requirement already satisfied: requests<3.0.0,>=2.33.0 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (2.34.2)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.44.0 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (1.45.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (1.84.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\ANACONDA\Lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in C:\ANACONDA\Lib\site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (49.0.0)
Requirement already satisfied: typing-extensions~=4.12 in C:\ANACONDA\Lib\site-packages (from grpcio<2.0.0,>=1.59.0->google-cloud-bigquery-storage) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.33.0->google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery-storage) (2026.6.17)
Requirement already satisfied: numpy>=1.24.0 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (2.4.6)
Requirement already satisfied: packaging>=24.2.0 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (26.0)
Requirement already satisfied: pandas<4.0.0,>=1.5.3 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (3.0.3)
Requirement already satisfied: pyarrow>=13.0.0 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (23.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\ANACONDA\Lib\site-packages (from pandas<4.0.0,>=1.5.3->db-dtypes) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\ANACONDA\Lib\site-packages (from pandas<4.0.0,>=1.5.3->db-dtypes) (2026.2)
Requirement already satisfied: cffi>=2.0.0 in C:\ANACONDA\Lib\site-packages (from cryptography>=41.0.5->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (2.1.0)
Requirement already satisfied: pycparser in C:\ANACONDA\Lib\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\ANACONDA\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-bigquery-storage) (0.6.4)
Requirement already satisfied: six>=1.5 in C:\ANACONDA\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4.0.0,>=1.5.3->db-dtypes) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [60]:

from google.cloud import bigquery

client = bigquery.Client(project="loanapp-0911")

query = """
SELECT
    COUNT(*) AS total_applications,
    COUNT(DISTINCT application_id) AS unique_applications
FROM `loanapp-0911.loan_demo.loan_master_data`
"""

result = client.query(query).to_dataframe()

print("BigQuery query succeeded!")
print("Total applications:", result.loc[0, "total_applications"])
print("Unique applications:", result.loc[0, "unique_applications"])

C:\ANACONDA\Lib\site-packages\google\auth\_default.py:113: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

BigQuery query succeeded!
Total applications: 52
Unique applications: 52

In [61]:

%pip install google-cloud-bigquery google-cloud-bigquery-storage db-dtypes

Requirement already satisfied: google-cloud-bigquery in C:\ANACONDA\Lib\site-packages (3.46.2)
Requirement already satisfied: google-cloud-bigquery-storage in C:\ANACONDA\Lib\site-packages (2.43.0)
Requirement already satisfied: db-dtypes in C:\ANACONDA\Lib\site-packages (1.9.0)
Requirement already satisfied: google-api-core<3.0.0,>=2.28.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (2.43.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in C:\ANACONDA\Lib\site-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.62.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.8.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.11.0)
Requirement already satisfied: packaging>=24.2.0 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (26.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in C:\ANACONDA\Lib\site-packages (from google-cloud-bigquery) (2.34.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.69.2 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.76.0)
Requirement already satisfied: protobuf<8.0.0,>=6.33.5 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (6.33.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.26.1 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.29.0)
Requirement already satisfied: opentelemetry-api<2.0.0,>=1.44.0 in C:\ANACONDA\Lib\site-packages (from google-api-core<3.0.0,>=2.28.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.45.1)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.84.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.59.0 in C:\ANACONDA\Lib\site-packages (from google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (1.84.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in C:\ANACONDA\Lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=41.0.5 in C:\ANACONDA\Lib\site-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (49.0.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in C:\ANACONDA\Lib\site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.9.0)
Requirement already satisfied: typing-extensions~=4.12 in C:\ANACONDA\Lib\site-packages (from grpcio<2.0.0,>=1.59.0->google-api-core[grpc]<3.0.0,>=2.28.0->google-cloud-bigquery) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\ANACONDA\Lib\site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\ANACONDA\Lib\site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.6.17)
Requirement already satisfied: numpy>=1.24.0 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (2.4.6)
Requirement already satisfied: pandas<4.0.0,>=1.5.3 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (3.0.3)
Requirement already satisfied: pyarrow>=13.0.0 in C:\ANACONDA\Lib\site-packages (from db-dtypes) (23.0.1)
Requirement already satisfied: tzdata in C:\ANACONDA\Lib\site-packages (from pandas<4.0.0,>=1.5.3->db-dtypes) (2026.2)
Requirement already satisfied: cffi>=2.0.0 in C:\ANACONDA\Lib\site-packages (from cryptography>=41.0.5->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.1.0)
Requirement already satisfied: pycparser in C:\ANACONDA\Lib\site-packages (from cffi>=2.0.0->cryptography>=41.0.5->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in C:\ANACONDA\Lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.4)
Note: you may need to restart the kernel to use updated packages.